### ISSUE TITLE
Is this still a thing?

### ISSUE THREAD

**Issue by 1j01** [minimill/spire#53]
Is the public instance at https://spire.minimill.co meant to be used?
A board I created previously appears to be gone.

Is development going to continue?

**Comment by 1j01** [comment]
I guess not, for now at least.

**Comment by schlosser** [comment]
It isn't sorry for the delayed response.

It was ultimately a side project which we're not supporting well.

Feel free to fork this and spin up your own version, though!

**Comment by 1j01** [comment]
Okay, I don't have a particular need for this tool, but I'll watch the repo for any further developments.
